AWSTemplateFormatVersion: 2010-09-09
Resources:
  immutableInfraestructureUser:
    Type: 'AWS::IAM::User'
    Properties:
      UserName: immutable-infraestructure-user
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonEC2FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonRoute53FullAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
        - 'arn:aws:iam::aws:policy/IAMFullAccess'
        - 'arn:aws:iam::aws:policy/AmazonVPCFullAccess'
Outputs:
    immutableInfraestructureUser:
        Value: !Ref immutableInfraestructureUser
        Description: User